name=microTelegramAPI
version=1.1.0
author=Serhii Lebedenko
maintainer=Serhii Lebedenko (slebedenko@gmail.com)
sentence=A simple library implementing basic Telegram API functions.
paragraph=Various transport types are supported, such as GSM modems.
category=Communication
url=https://github.com/SerhiiLe/microTelegramAPI
depends=ArduinoJson (>=7.0.0)
architectures=*