name=microTelegramAPI
version=1.0.0
author=Serhii Lebedenko (slebedenko@gmail.com)
maintainer=Serhii Lebedenko (slebedenko@gmail.com)
sentence=A very simple library implementing basic Telegram API functions.
paragraph=A very simple library that implements basic Telegram API functions without directly using the network. This allows the use of both standard libraries and third-party ones, such as GSM modems.
category=Device Communication
url=https://github.com/SerhiiLe/microTelegramAPI
architectures=*